/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro;

import SQL.ShareConnection;
import java.awt.Component;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author luis
 */
public class RegistroEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form RegistroEstudiante
     */
        java.sql.PreparedStatement statement = null;
        java.sql.ResultSet result = null;
        String sql = null;
        JTable leer = new JTable();
        int asientos_asignados = 0;
        
    public RegistroEstudiante() {
        initComponents();
        setLocationRelativeTo(null);
         datoCiclo();
        //setComboboxCiclo();
         datoBus();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ciclo = new javax.swing.JComboBox();
        AddCiclo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CarneText = new javax.swing.JTextField();
        NombreText = new javax.swing.JTextField();
        ApellidoText = new javax.swing.JTextField();
        TelefonoText = new javax.swing.JTextField();
        AddEstudiante = new javax.swing.JButton();
        AddBus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bus = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        regBus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AddCiclo.setText("Nuevo");
        AddCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCicloActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar ciclo:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estudiante")));

        jLabel2.setText("Carne:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Telefono:");

        AddEstudiante.setText("Guardar");
        AddEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarneText, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(NombreText)
                    .addComponent(ApellidoText)
                    .addComponent(TelefonoText))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(AddEstudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CarneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ApellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TelefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddEstudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddBus.setText("Nuevo");
        AddBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBusActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccionar bus:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        jLabel7.setText("Generar registros (por bus):");

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver todos los registros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(regBus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ciclo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AddCiclo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCiclo))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBus))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCicloActionPerformed
        // TODO add your handling code here:
        String nuevoCiclo = JOptionPane.showInputDialog("Ingrese el nuevo ciclo");
        sql = "insert into Convencion.Ciclo(ciclo) values(?)";
            try {
                statement = ShareConnection.connection.getConn().prepareStatement(sql);
                statement.setString(1, nuevoCiclo);
                //result = statement.executeQuery(sql);
                statement.execute();
                statement.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al ingresar los datos: " + ex.getMessage());
            }
        datoCiclo();
    }//GEN-LAST:event_AddCicloActionPerformed

    private void AddEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEstudianteActionPerformed
        // TODO add your handling code here:
        ////    verificacion del bus    ////
        sql = "select count(*) from convencion.asientos where Bus_idBus = ?";
        try {
            statement = ShareConnection.connection.getConn().prepareStatement(sql);
            statement.setString(1, String.valueOf(bus.getSelectedIndex()+1));
            result = statement.executeQuery();
            leer.setModel(DbUtils.resultSetToTableModel(result));
            statement.close();
            result.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror: " + e.getMessage());
        }
        
        asientos_asignados = 0;
        asientos_asignados = Integer.parseInt(leer.getValueAt(0, 0).toString());
        //System.out.println(leer.getValueAt(0, 0).toString());
        
        if(asientos_asignados < 45){
            //// ingresa usuario
        sql = "insert into convencion.estudiante(carne, nombre, apellido, telefono, fecha, ciclo_id) values(?, ?, ?, ?, CURDATE(), ?)";
            try {
                statement = ShareConnection.connection.getConn().prepareStatement(sql);
                statement.setString(1, CarneText.getText());
                statement.setString(2, NombreText.getText());
                statement.setString(3, ApellidoText.getText());
                statement.setString(4, TelefonoText.getText());
                statement.setString(5, String.valueOf(ciclo.getSelectedIndex()+1));
                //result = statement.executeQuery(sql);
                statement.execute();
                statement.close();
                result.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al ingresar los datos: " + ex.getMessage());
            }
            /// fin ingresa usuario ////
            
            ////    asignacion de su asiento    ////
            sql = "insert into convencion.asientos(Bus_idBus, Estudiante_idEstudiante) values( ?, (select idEstudiante from convencion.estudiante where carne = ?))";
            try {
                statement = ShareConnection.connection.getConn().prepareStatement(sql);
                statement.setString(1, String.valueOf(bus.getSelectedIndex()+1));
                statement.setString(2, CarneText.getText());
                //result = statement.executeQuery(sql);
                statement.execute();
                statement.close();
                result.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al ingresar los datos: " + ex.getMessage());
            }
            
        }
        else JOptionPane.showMessageDialog(null, "Seleccione otro bus este esta lleno");
        
        ////    verificacion del bus    ////
        
        //  carne text  //
        //boleta b = new boleta(CarneCopia);
        NewJFrame f = new NewJFrame(CarneText.getText());
        //  carne text  //
        
        CarneText.setText(null);
        NombreText.setText(null);
        ApellidoText.setText(null);
        TelefonoText.setText(null);
        
    }//GEN-LAST:event_AddEstudianteActionPerformed

    private void AddBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBusActionPerformed
        // TODO add your handling code here:
        String nuevoBus = JOptionPane.showInputDialog("Ingrese el nuevo bus");
        sql = "insert into convencion.bus(bus) values(?)";
            try {
                statement = ShareConnection.connection.getConn().prepareStatement(sql);
                statement.setString(1, nuevoBus);
                statement.execute();
                statement.close();
            } catch (SQLException ex) {
                Logger.getLogger(RegistroEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al ingresar los datos: " + ex.getMessage());
            }
        datoBus();
    }//GEN-LAST:event_AddBusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Listado l = new Listado(regBus.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Listado l = new Listado("all");
    }//GEN-LAST:event_jButton2ActionPerformed

       public void setComboboxCiclo(){
          try{
            this.sql="select * from ciclo";
            statement = ShareConnection.connection.getConn().prepareStatement(sql);
            result = statement.executeQuery();
            
            while(result.next()){
                String ciclo = result.getString("ciclo");
                this.ciclo.addItem(ciclo);
            }
            statement.close();
            result.close();
        }catch(Exception e){
            
        }
          
          
            
    }//finaliza seComboBox
    
    
    
    public void datoCiclo(){
        ciclo.removeAllItems();
        sql = "select ciclo from convencion.ciclo";
        try {
            statement = ShareConnection.connection.getConn().prepareStatement(sql);
            result = statement.executeQuery();
            leer.setModel(DbUtils.resultSetToTableModel(result));
            statement.close();
            result.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos: " + e.getMessage());
        }
        
        DefaultTableModel model = (DefaultTableModel) leer.getModel();
        for (int i = 0; i < model.getDataVector().size(); i++) {
            ciclo.addItem(model.getValueAt(i, 0).toString());
            //System.out.println(model.getValueAt(i, 0).toString());
        }
    }
    
    public void datoBus(){
        bus.removeAllItems();
        regBus.removeAllItems();
        sql = "select bus from convencion.bus";
        try {
            statement = ShareConnection.connection.getConn().prepareStatement(sql);
            result = statement.executeQuery();
            leer.setModel(DbUtils.resultSetToTableModel(result));
            statement.close();
            result.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos: " + e.getMessage());
        }
        
        DefaultTableModel model = (DefaultTableModel) leer.getModel();
        for (int i = 0; i < model.getDataVector().size(); i++) {
            bus.addItem(model.getValueAt(i, 0).toString());
            regBus.addItem(model.getValueAt(i, 0).toString());
            //System.out.println(model.getValueAt(i, 0).toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBus;
    private javax.swing.JButton AddCiclo;
    private javax.swing.JButton AddEstudiante;
    private javax.swing.JTextField ApellidoText;
    private javax.swing.JTextField CarneText;
    private javax.swing.JTextField NombreText;
    private javax.swing.JTextField TelefonoText;
    private javax.swing.JComboBox bus;
    private javax.swing.JComboBox ciclo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> regBus;
    // End of variables declaration//GEN-END:variables
}
